#!/bin/bash
set -eo pipefail

repository=$1
app=${1%.git}
sha=$2
username=$3
fingerprint=$4

URL=http://$CONTROLLER_HOST:$CONTROLLER_PORT/api/apps/$app/push

curl \
  -X 'POST' --fail \
  -H 'Content-Type: application/json' \
  -H "X-Deis-Builder-Auth: $BUILDER_KEY" \
  -d "{\"receive_user\": \"$username\", \"receive_repo\": \"$app\", \"sha\": \"$sha\", \"fingerprint\": \"$fingerprint\", \"ssh_connection\": \"$SSH_CONNECTION\", \"ssh_original_command\": \"$SSH_ORIGINAL_COMMAND\"}" \
  --silent $URL >/dev/null
  