#!/bin/bash

# start an SSH daemon to process `git push` requests
/usr/sbin/sshd -D -e &
SSHD_PID=$!

# spawn a docker daemon to run builds
/usr/local/bin/docker -d &
DOCKER_PID=$!

# out on SIGINT and SIGTERM
trap "kill -TERM $SSHD_PID $DOCKER_PID; wait $SSHD_PID; wait $DOCKER_PID" INT TERM
wait
