#!/bin/bash
#
# build hook called on every git receive-pack
#
RECEIVE_USER=$1
RECEIVE_REPO=$2

cd $RECEIVE_REPO && mkdir -p build
tmpdir=$(mktemp --tmpdir=build -d)
image=$RECEIVE_USER/${RECEIVE_REPO%.git}
#target={{ .deis_registry_host }}:{{ .deis_registry_port }}/$image
git archive master | tar --extract -C $tmpdir
sudo docker build -t $image $tmpdir >&2
sudo docker tag $image $target >&2
sudo docker push $target >&2
rm -rf $tmpdir
